sector_to_boards:
  科技:
    - "半导体"
    - "软件开发"
    - "计算机设备"
    - "通信设备"
    - "电子元件"
    - "互联网服务"
  消费:
    - "食品饮料"
    - "酿酒行业"
    - "家电行业"
    - "汽车整车"
    - "旅游酒店"
    - "商业百货"
  医疗:
    - "化学制药"
    - "中药"
    - "生物制品"
    - "医疗器械"
    - "医药商业"
    - "医疗服务"
  新能源:
    - "电池"
    - "光伏设备"
    - "风电设备"
    - "电网设备"
    - "汽车零部件"
  军工:
    - "航天航空"
    - "船舶制造"
    - "地面兵装"
  金融:
    - "银行"
    - "保险"
    - "证券"
    - "多元金融"
  房地产:
    - "房地产开发"
    - "房地产服务"
    - "装修建材"
    - "水泥建材"
  有色金属:
    - "有色金属"
    - "贵金属"
    - "能源金属"
    - "小金属"
